RPCSX-GPU & RPCSX-OS Merge Update
RPCSX/wiki pull request #5
Opened 2024-10-12 19:13 UTC by Darkhost1999

Update the commands for running RPCSX
Add audio dependencies
Remove outdated information about Virtual HDD
Tease upcoming WSL information
Overall review and evaluate the information and ensure accuracy.

2024-10-12 19:15 UTC, Darkhost1999 commented
$ rubocop
Inspecting 8 files
........

8 files inspected, no offenses detected

2024-10-17 18:53 UTC, Darkhost1999 commented
https://github.com/RPCSX/rpcsx/commit/7e7a56f0e2c96381140c149581b0bbc1a0503001

I can update running.md with arguments simplification. Or should I add the information as basic/advanced commands?

2024-10-18 00:52 UTC, OCDkirby requested changes

2024-10-18 00:52 UTC, OCDkirby commented on install-guide.md
> +sudo pacman -S libunwind glfw-x11 vulkan-devel sox git cmake alsa-lib nasm
`--needed` should be preserved

2024-10-18 00:53 UTC, OCDkirby commented
> https://github.com/RPCSX/rpcsx/commit/7e7a56f0e2c96381140c149581b0bbc1a0503001
> 
> I can update running.md with arguments simplification. Or should I add the information as basic/advanced commands?

Maybe add it as an optional argument under see the relevant command?

2024-10-18 01:59 UTC, Darkhost1999 commented
I'm going to sleep. Maybe I'll add something like this in the morning.
```
##Booting Firmware
Standard Syntax
./rpcsx --system --mount /path/to/firmware/md0/ / /mini-syscore.elf

Simplified Syntax
./rpcsx --fw /path/to/firmware

##Booting Games
Standard Syntax
./rpcsx --mount /path/to/firmware/md0/ / --mount /path/to/game/app0 /app0 /app0/eboot.bin [optional args without brackets]

Simplified Syntax
./rpcsx --fw /path/to/firmware /path/to/game/

For most samples, you still need to specify mount points, e.g.
--fw /path/to/firmware--mount /path/to/api_gnm/directory/ /app0 /app0/basic-sample/basic-sample_debug.elf
```

2024-10-26 12:48 UTC, Darkhost1999 commented
Seems unnecessary. They can ask on Discord if syntax can be simplified but nothing wrong with being more detailed or specific about what you want to load. Especially at this time. Maybe simplify the context at 12% compatibility database for 5k games listed.

2024-11-10 01:55 UTC, OCDkirby approved these changes

2024-11-10 01:56 UTC, merged